### ISSUE TITLE
Better not use your own settings file

### ISSUE THREAD

**Issue by FichteFoll** [SublimeText/RevertFontSize#1]
Instead of using your own settings file for one settings you could just use the existing files and read them.

You can also create a file in your plugin's dir, name it "Preferences.sublime-settings" and it will be considered when loading the "default" preferences which you are doing anyway.

**Comment by jsadeli** [comment]
Hi there, the reason why this plugin uses its own settings is because it needs to know what value to revert to. Sublime Text's default `font_size` is set to `10` while the user-facing `font_size` changes whenever it gets adjusted (`Preferences >> Font >> Larger` -or- `Smaller`). The built-in font reset command (`Preferences >> Font >> Reset`) just removes the user-facing `font_size` setting, which causes Sublime Text to use the `font_size` value from default setting.

In my case, I like using `Ubuntu Mono` font with a size of `13`. Whenever I do a presentation, I tend to increase the font size to at least `18` for viewer readability. After the presentation, I like to quickly revert back to my preferred font size value of `13`. If the plugin uses Sublime Text's default setting (from `Default\Preferences.sublime-settings`), it'll revert back to `10` (which isn't the 'correct' one). If it uses the current user setting (from `User\Preferences.sublime-settings`), it'll see `18` (which isn't correct either).

That is the reasoning behind the plugin's own preferences file since I'm not sure if there's another way to do this under the current Sublime Text 2 behavior (build 2217).

**Comment by FichteFoll** [comment]
I think you do not quite understand the behaviour of setting files with the same file name. [This](https://www.sublimetext.com/docs/2/settings.html) is the loading precedence. What I'd wanted to do was create a `"Preferences.sublime-settings"` file in the package dir with the same setting name (`"default_font_size"`) and further use `sublime.load_settings("Preferences.sublime-settings")`.

However, what I thought you would be able to do does not work with the `"Preferences.sublime-settings"` file name because of _whatever reason_. So, your only option for what I suggested is to hardcode the default value of `10` and let the user alter his user settings. Then you would be able to load the setting using `view.settings().get("default_font_size")` and this considers project settings and view-specific settings as well.

The reason why I am suggesting this is because I don't really like having 20 `.sublime-settings` files in my User package which just have one or two keys in it. That could've been easily merged into the main user settings file.

**Comment by jsadeli** [comment]
Aaah, I understand now. Ok, I'll give it a try later this week.

**Comment by jsadeli** [comment]
Updated plugin's settings behavior at commit [bdb4bf9d...](https://github.com/SublimeText/RevertFontSize/commit/bdb4bf9d3ebb9d23973ab581fff68fc2ddfd0189) per suggestion, thanks.

**Comment by FichteFoll** [comment]
Glad to be of help. Well, with that change you still load the setting via `load_settings` and only consider the actual file settings but still better than before. There is limited usage to setting this in the project settings ... although, the other settings (like font size or font face) can be changed per-project as well.
